#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// 定义源文件路径
const srcDir = path.join(__dirname, 'src');
const outputDir = path.join(__dirname, 'dist');
const outputFile = path.join(outputDir, 'bilibili-blacklist.user.js');

// 确保输出目录存在
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// 定义模块加载顺序
const moduleOrder = [
  'storage/storage.js',
  'core/core.js',
  'core/video-data.js',
  'ui/ui.js',
  'observer/observer.js',
  'pages/pages.js',
  'ads/ads.js',
  'utils/utils.js',
  'autoplay/autoplay.js',
  'main.js' // 主文件放在最后，包含初始化代码
];

// 读取所有模块文件并按顺序合并
let outputContent = '';

// 首先添加全局变量和函数定义的包装
outputContent += '// ==UserScript==\n';
outputContent += '// @name         Bilibili-BlackList\n';
outputContent += '// @namespace    https://github.com/HeavenTTT/bilibili-blacklist\n';
outputContent += '// @version      1.2.3\n';
outputContent += '// @author       HeavenTTT\n';
outputContent += '// @description  Bilibili UP屏蔽插件 - 屏蔽UP主视频卡片，支持精确匹配和正则匹配，支持视频页面、分类页面、搜索页面等。\n';
outputContent += '// @match        *://*.bilibili.com/*\n';
outputContent += '// @grant        GM_setValue\n';
outputContent += '// @grant        GM_getValue\n';
outputContent += '// @grant        GM_addStyle\n';
outputContent += '// @icon         https://www.bilibili.com/favicon.ico\n';
outputContent += '// @license      MIT\n';
outputContent += '// @downloadURL https://update.greasyfork.org/scripts/533940/Bilibili-BlackList.user.js\n';
outputContent += '// @updateURL https://update.greasyfork.org/scripts/533940/Bilibili-BlackList.meta.js\n';
outputContent += '// ==/UserScript==\n\n';

outputContent += '(function () {\n  "use strict";\n\n  /*\n   * Bilibili-BlackList -- Bilibili UP屏蔽插件\n   * 脚本大部分代码由AI生成，作者一点都不懂JavaScript，出现bug请联系Gemini / ChatGPT / DeepSeek\n   * this script is mainly generated by AI, the author doesn\'t know JavaScript at all, if there are bugs, please contact Gemini / ChatGPT / DeepSeek\n   * 感谢你的使用\n   * Thank you for using this script\n   *\n   * 本段注释为VS code 自动生成 this is a comment generated by VS code\n   */\n\n';

// 首先添加所有模块的变量和函数定义
for (const modulePath of moduleOrder) {
  const fullPath = path.join(srcDir, modulePath);
  if (fs.existsSync(fullPath)) {
    let content = fs.readFileSync(fullPath, 'utf8');
    
    // 对于主文件，移除其外层包装器
    if (modulePath === 'main.js') {
      // 手动处理主文件：移除开头的 "(function () {" 和 "  \"use strict\";" 以及结尾的 "});"
      const lines = content.split('\n');
      content = '';
      let skipFirstLines = 2; // 跳过开头两行：函数定义和"use strict"
      let skipLastLines = 1;  // 跳过最后一行：结束的 });
      
      for (let i = 0; i < lines.length; i++) {
        if (i < skipFirstLines || i >= lines.length - skipLastLines) {
          continue; // 跳过需要移除的行
        }
        content += lines[i] + '\n';
      }
    } else {
      // 对于其他模块，移除函数包装但保留内容
      content = content
        .replace(/^function\s+\w+\s*\(\)\s*{/, '') // 移除函数定义开始
        .replace(/\s*}\s*$/, ''); // 移除函数定义结束
    }
    
    outputContent += content + '\n';
  } else {
    console.warn(`Warning: Module file not found: ${fullPath}`);
  }
}

outputContent += '\n})();\n';

// 将合并后的内容写入输出文件
fs.writeFileSync(outputFile, outputContent);

console.log(`Build completed: ${outputFile}`);
console.log(`Total modules processed: ${moduleOrder.length}`);